/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javaswing.studentmanagement;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DatIT
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    ListStudent lst = new ListStudent();

    public mainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jLbName = new javax.swing.JLabel();
        jTextFieldMSSV = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLbN = new javax.swing.JLabel();
        jLbName2 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLbName3 = new javax.swing.JLabel();
        jLbName4 = new javax.swing.JLabel();
        jTextFieldGpa = new javax.swing.JTextField();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");

        jLabelTitle.setFont(new java.awt.Font("Be Vietnam", 0, 14)); // NOI18N
        jLabelTitle.setText("THÔNG TIN SINH VIÊN");

        jLbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName.setText("MSSV");

        jTextFieldMSSV.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldMSSV.setText("Mã số sinh viên");
        jTextFieldMSSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMSSVMouseClicked(evt);
            }
        });
        jTextFieldMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMSSVActionPerformed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldName.setText("Họ và tên");
        jTextFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseClicked(evt);
            }
        });
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLbN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbN.setText("Tên SV");

        jLbName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName2.setText("Địa chỉ");

        jTextFieldAddress.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldAddress.setText("Tỉnh Thành Phố");
        jTextFieldAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAddressMouseClicked(evt);
            }
        });
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jLbName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName3.setText("GPA");

        jLbName4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName4.setText("Giới tính");

        jTextFieldGpa.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldGpa.setText("Hệ 4");
        jTextFieldGpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldGpaMouseClicked(evt);
            }
        });
        jTextFieldGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGpaActionPerformed(evt);
            }
        });

        jRadioButtonNu.setText("Nữ");
        jRadioButtonNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNuActionPerformed(evt);
            }
        });

        jRadioButtonNam.setSelected(true);
        jRadioButtonNam.setText("Nam");
        jRadioButtonNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNamActionPerformed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 102, 102));
        jButtonUpdate.setText("Sửa");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(0, 153, 0));
        jButtonAdd.setText("Thêm");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDel.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 18)); // NOI18N
        jButtonDel.setForeground(new java.awt.Color(204, 0, 0));
        jButtonDel.setText("Xóa");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ và tên", "Địa chỉ", "Giới tính", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(10);
        }
        jTable2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbN)
                            .addComponent(jLbName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMSSV, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jTextFieldName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbName3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLbName4)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButtonNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbName2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbName4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonNu)
                            .addComponent(jRadioButtonNam)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMSSVActionPerformed

    private void jRadioButtonNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNuActionPerformed
        if (jRadioButtonNam.isSelected() == true)
            jRadioButtonNam.setSelected(false);
    }//GEN-LAST:event_jRadioButtonNuActionPerformed

    private void jRadioButtonNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNamActionPerformed
        if (jRadioButtonNu.isSelected() == true)
            jRadioButtonNu.setSelected(false);
    }//GEN-LAST:event_jRadioButtonNamActionPerformed

    private void jTextFieldMSSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMSSVMouseClicked
        jTextFieldMSSV.setText("");
    }//GEN-LAST:event_jTextFieldMSSVMouseClicked

    private void jTextFieldAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAddressMouseClicked
        // TODO add your handling code here:
        jTextFieldAddress.setText("");
    }//GEN-LAST:event_jTextFieldAddressMouseClicked

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed

    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGpaActionPerformed

    private void jTextFieldGpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldGpaMouseClicked
        // TODO add your handling code here:
        jTextFieldGpa.setText("");
    }//GEN-LAST:event_jTextFieldGpaMouseClicked

    private void jTextFieldNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseClicked
        // TODO add your handling code here:
        jTextFieldName.setText("");
    }//GEN-LAST:event_jTextFieldNameMouseClicked

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String name;
        String address;
        boolean sex;
        double gpa;
        String id;

        try {
            name = jTextFieldName.getText();
            address = jTextFieldAddress.getText();
            gpa = Double.parseDouble(jTextFieldGpa.getText());
            id = jTextFieldMSSV.getText();
            if (jRadioButtonNam.isSelected() == true) {
                sex = true;
            } else {
                sex = false;
            }
            Student st = new Student(id, name, address, sex, gpa);
            //pass value for attribute student from jTextField
            if (lst.checkingIDStudent(st)) {
                lst.addStudent(st);

                ////add data in jTable
                JOptionPane.showMessageDialog(this, "Thêm thành công !!!");
                DefaultTableModel tblModel1 = (DefaultTableModel) jTable2.getModel();
                List<String> data = new ArrayList<String>();
                data.add(st.getId());
                data.add(st.getName());
                data.add(st.getAddress());
                data.add((st.getSex()) ? "Nam" : "Nữ");
                data.add(st.getGpa() + "");

                tblModel1.addRow(data.toArray());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Trùng mã số sinh viên !!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng dữ liệu đầu vào");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed

        String idDel = JOptionPane.showInputDialog("Nhập vào id cần xóa");
        int index = lst.removeStudent(idDel);
        if (index != lst.getLstStudent().size()) {
            JOptionPane.showMessageDialog(this, "Xóa thành công!!!");
            DefaultTableModel tblModel1 = (DefaultTableModel) jTable2.getModel();
            tblModel1.removeRow(index);

        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại kiểm tra id !!");
        }

    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        String idEdit = JOptionPane.showInputDialog(rootPane, "Nhập vào MSSV cần sửa:");
        Student stEdit = lst.findStudentByID(idEdit);
        if (stEdit != null) {
            inputJFrame jIF = new inputJFrame();
            jIF.setVisible(true);
            jIF.setValueStudent(stEdit);
        }
        else
            JOptionPane.showMessageDialog(this, "Không tìm thấy id nào trùng khớp!!!");


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    public void editStudentHomeF(Student st){
        lst.updateInfoStudent(st);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLbN;
    private javax.swing.JLabel jLbName;
    private javax.swing.JLabel jLbName2;
    private javax.swing.JLabel jLbName3;
    private javax.swing.JLabel jLbName4;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldGpa;
    private javax.swing.JTextField jTextFieldMSSV;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
