/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javaswing.studentmanagement;

import java.awt.HeadlessException;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DatIT
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    ListStudent lst = new ListStudent();

    public mainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jLbName = new javax.swing.JLabel();
        jTextFieldMSSV = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLbN = new javax.swing.JLabel();
        jLbName2 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLbName3 = new javax.swing.JLabel();
        jLbName4 = new javax.swing.JLabel();
        jTextFieldGpa = new javax.swing.JTextField();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnDone = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");

        jLabelTitle.setFont(new java.awt.Font("Be Vietnam", 0, 14)); // NOI18N
        jLabelTitle.setText("THÔNG TIN SINH VIÊN");

        jLbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName.setText("MSSV");

        jTextFieldMSSV.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldMSSV.setText("Mã số sinh viên");
        jTextFieldMSSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMSSVMouseClicked(evt);
            }
        });
        jTextFieldMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMSSVActionPerformed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldName.setText("Họ và tên");
        jTextFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseClicked(evt);
            }
        });
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLbN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbN.setText("Tên SV");

        jLbName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName2.setText("Địa chỉ");

        jTextFieldAddress.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldAddress.setText("Tỉnh Thành Phố");
        jTextFieldAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAddressMouseClicked(evt);
            }
        });
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jLbName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName3.setText("GPA");

        jLbName4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbName4.setText("Giới tính");

        jTextFieldGpa.setFont(new java.awt.Font("Be Vietnam", 2, 14)); // NOI18N
        jTextFieldGpa.setText("Hệ 4");
        jTextFieldGpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldGpaMouseClicked(evt);
            }
        });
        jTextFieldGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGpaActionPerformed(evt);
            }
        });

        jRadioButtonNu.setText("Nữ");
        jRadioButtonNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNuActionPerformed(evt);
            }
        });

        jRadioButtonNam.setSelected(true);
        jRadioButtonNam.setText("Nam");
        jRadioButtonNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNamActionPerformed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 102, 102));
        jButtonUpdate.setText("Sửa");
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(81, 35));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(0, 153, 0));
        jButtonAdd.setText("Thêm");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDel.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 18)); // NOI18N
        jButtonDel.setForeground(new java.awt.Color(204, 0, 0));
        jButtonDel.setText("Xóa");
        jButtonDel.setPreferredSize(new java.awt.Dimension(81, 35));
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ và tên", "Địa chỉ", "Giới tính", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(10);
        }
        jTable2.getAccessibleContext().setAccessibleName("");

        btnDone.setBackground(new java.awt.Color(0, 102, 0));
        btnDone.setFont(new java.awt.Font("Be Vietnam", 1, 14)); // NOI18N
        btnDone.setForeground(new java.awt.Color(255, 255, 255));
        btnDone.setText("Done");
        btnDone.setEnabled(false);
        btnDone.setPreferredSize(new java.awt.Dimension(81, 35));
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Đọc Ghi File"));

        jButton1.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("RF");
        jButton1.setActionCommand("Read");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Be Vietnam SemiBold", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("WF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("btnReadFile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitle)
                        .addGap(264, 264, 264))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbN)
                            .addComponent(jLbName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMSSV, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jTextFieldName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbName3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLbName4)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButtonNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelTitle)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbName2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbName4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonNu)
                    .addComponent(jRadioButtonNam))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMSSVActionPerformed

    private void jRadioButtonNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNuActionPerformed
        if (jRadioButtonNam.isSelected() == true)
            jRadioButtonNam.setSelected(false);
    }//GEN-LAST:event_jRadioButtonNuActionPerformed

    private void jRadioButtonNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNamActionPerformed
        if (jRadioButtonNu.isSelected() == true)
            jRadioButtonNu.setSelected(false);
    }//GEN-LAST:event_jRadioButtonNamActionPerformed

    private void jTextFieldMSSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMSSVMouseClicked
        jTextFieldMSSV.setText("");
    }//GEN-LAST:event_jTextFieldMSSVMouseClicked

    private void jTextFieldAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAddressMouseClicked
        // TODO add your handling code here:
        jTextFieldAddress.setText("");
    }//GEN-LAST:event_jTextFieldAddressMouseClicked

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed

    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGpaActionPerformed

    private void jTextFieldGpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldGpaMouseClicked
        // TODO add your handling code here:
        jTextFieldGpa.setText("");
    }//GEN-LAST:event_jTextFieldGpaMouseClicked

    private void jTextFieldNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseClicked
        // TODO add your handling code here:
        jTextFieldName.setText("");
    }//GEN-LAST:event_jTextFieldNameMouseClicked

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String name;
        String address;
        boolean sex;
        double gpa;
        String id;

        try {
            name = jTextFieldName.getText();
            address = jTextFieldAddress.getText();
            gpa = Double.parseDouble(jTextFieldGpa.getText());
            id = jTextFieldMSSV.getText();
            if (jRadioButtonNam.isSelected() == true) {
                sex = true;
            } else {
                sex = false;
            }
            Student st = new Student(id, name, address, sex, gpa);
            //pass value for attribute student from jTextField
            if (lst.addStudent(st)) {

                showDataInJTable(st);
                ////add data in jTable
                JOptionPane.showMessageDialog(this, "Thêm thành công !!!");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Trùng mã số sinh viên !!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng dữ liệu đầu vào");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed

        String idDel = JOptionPane.showInputDialog("Nhập vào id cần xóa");
        int index = lst.findIndexStudent(idDel);
        if (lst.removeStudent(idDel)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công!!!");
            DefaultTableModel tblModel1 = (DefaultTableModel) jTable2.getModel();
            tblModel1.removeRow(index);

        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại kiểm tra id !!");
        }

    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        String idEdit = JOptionPane.showInputDialog(rootPane, "Nhập vào MSSV cần sửa:");
        Student stEdit = lst.findStudentByID(idEdit);
        if (stEdit != null) {
            JOptionPane.showMessageDialog(rootPane, "Tìm thành công SV:[" + idEdit
                    + "]\n Nhập thông tin bên dưới");
            jTextFieldName.setText(stEdit.getName());
            jTextFieldMSSV.setText(stEdit.getId());
            jTextFieldMSSV.setEnabled(false);
            jTextFieldAddress.setText(stEdit.getAddress());
            jTextFieldGpa.setText(stEdit.getGpa() + "");
            if (stEdit.getSex()) {
                if (jRadioButtonNam.isSelected()) {
                    jRadioButtonNam.setSelected(true);
                    jRadioButtonNu.setSelected(false);
                } else {
                    jRadioButtonNam.setSelected(false);
                    jRadioButtonNu.setSelected(true);
                }
            }
            btnDone.setEnabled(true);
            jButtonAdd.setEnabled(false);
            jButtonDel.setEnabled(false);
            jButtonUpdate.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!!!");
        }


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:

        try {
            String id = jTextFieldMSSV.getText();
            String name = jTextFieldName.getText();
            String address = jTextFieldAddress.getText();
            double gpa = Double.parseDouble(jTextFieldGpa.getText());
            boolean sex;
            if (jRadioButtonNam.isSelected()) {
                sex = true;
            } else {
                sex = false;
            }
            Student stEdit = new Student(id, name, address, sex, gpa);
            if (lst.updateInfoStudent(stEdit)) {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật không thành công");
            }
            DefaultTableModel tblModel1 = (DefaultTableModel) jTable2.getModel();
            int index = lst.findIndexStudent(jTextFieldMSSV.getText());

            tblModel1.setValueAt(stEdit.getId(), index, 0);
            tblModel1.setValueAt(stEdit.getName(), index, 1);
            tblModel1.setValueAt(stEdit.getAddress(), index, 2);
            tblModel1.setValueAt((stEdit.getSex() ? "Nam" : "Nữ"), index, 3);
            tblModel1.setValueAt(String.valueOf(stEdit.getGpa()), index, 4);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi định dạng nhập!!");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi cập nhật!!");
        } finally {
            jTextFieldMSSV.setEnabled(true);
            btnDone.setEnabled(false);
            jButtonAdd.setEnabled(true);
            jButtonDel.setEnabled(true);
            jButtonUpdate.setEnabled(true);
        }


    }//GEN-LAST:event_btnDoneActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            FileOutputStream fos = new FileOutputStream("sinhvien_out.txt");
            OutputStreamWriter osw = new OutputStreamWriter(fos, "UTF-8");
            BufferedWriter bw = new BufferedWriter(osw);
            for (Student student : lst.getLstStudent()) {
                bw.write(student.getId() + "/");

                bw.write(student.getName() + "/");

                bw.write(student.getAddress() + "/");

                bw.write(student.getGpa() + "/");

                bw.write((student.getSex() ? "Nam" : "Nữ"));
                bw.newLine();
            }
            bw.close();
            osw.close();
            fos.close();
            JOptionPane.showMessageDialog(rootPane, "In ra file thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi xuất file thử lại !!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n = 0;
        try {
            n = Integer.parseInt(JOptionPane.
                    showInputDialog("Nhập số lượng SV thêm từ file !"));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi nhập vào !!!");
        }
        try {
            FileInputStream fis = new FileInputStream("sinhvien_inp.txt");
            InputStreamReader isr = new InputStreamReader(fis, "UTF-8");
            BufferedReader br = new BufferedReader(isr);
            String id, name, address;
            double gpa;
            boolean sex;
            int complete = 0;

            for (int i = 0; i < n; i++) {
                id = br.readLine();
                name = br.readLine();
                address = br.readLine();
                sex = Boolean.parseBoolean(br.readLine());
                gpa = Double.parseDouble(br.readLine());
                if (lst.addStudent(new Student(id, name, address, sex, gpa))) {
                    showDataInJTable(new Student(id, name, address, sex, gpa));
                    complete++;
                }

            }
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công:"+complete+" | Thất bại"+
                    (n-complete));
            br.close();
            isr.close();
            fis.close();
        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Đọc file thất bại vui lòng thử lại");
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    void showDataInJTable(Student st) {
        DefaultTableModel tblModel1 = (DefaultTableModel) jTable2.getModel();
        List<String> data = new ArrayList<String>();
        data.add(st.getId());
        data.add(st.getName());
        data.add(st.getAddress());
        data.add((st.getSex()) ? "Nam" : "Nữ");
        data.add(st.getGpa() + "");

        tblModel1.addRow(data.toArray());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLbN;
    private javax.swing.JLabel jLbName;
    private javax.swing.JLabel jLbName2;
    private javax.swing.JLabel jLbName3;
    private javax.swing.JLabel jLbName4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldGpa;
    private javax.swing.JTextField jTextFieldMSSV;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
